# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '17.0'
prepare_react_native_project!

use_modular_headers!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

project 'DriverClient.xcodeproj'

target 'DriverClient' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # Xcode 27 fix: Disable explicit modules at the project level
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
      config.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
        config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
        config.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'
      end

      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = [
            '$(inherited)',
            'FMT_USE_CONSTEVAL=0'
          ]
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = [
            '$(inherited)',
            '-DFMT_USE_CONSTEVAL=0'
          ]
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++17'
        end
      end
    end

    # Fix: Remove duplicate 'react_runtime' module in React-jsitooling to avoid
    # "Redefinition of module 'react_runtime'" error (React-RuntimeCore already defines it)
    jsitooling_modulemap = File.join(installer.sandbox.root, 'Headers', 'Public', 'react_runtime', 'React-jsitooling.modulemap')
    if File.exist?(jsitooling_modulemap)
      File.delete(jsitooling_modulemap)
    end

    # Fix: Remove duplicate 'ReactCommon' module in React-RuntimeApple to avoid
    # "Redefinition of module 'ReactCommon'" error (ReactCommon.modulemap already defines it)
    runtime_apple_modulemap = File.join(installer.sandbox.root, 'Headers', 'Public', 'ReactCommon', 'React-RuntimeApple.modulemap')
    if File.exist?(runtime_apple_modulemap)
      File.delete(runtime_apple_modulemap)
    end

    # Update all xcconfig files that referenced the deleted modulemaps
    Dir.glob(File.join(installer.sandbox.root, 'Target Support Files', '**', '*.xcconfig')).each do |xcconfig_path|
      xcconfig_content = File.read(xcconfig_path)
      modified = false
      if xcconfig_content.include?('React-jsitooling.modulemap')
        xcconfig_content.gsub!('React-jsitooling.modulemap', 'React-RuntimeCore.modulemap')
        modified = true
      end
      if xcconfig_content.include?('React-RuntimeApple.modulemap')
        xcconfig_content.gsub!('React-RuntimeApple.modulemap', 'ReactCommon.modulemap')
        modified = true
      end
      File.write(xcconfig_path, xcconfig_content) if modified
    end


    # Also force the main Pods project to target iOS 17.0
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
